# Generated by Django 5.2 on 2025-04-24 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jeux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('plateforme', models.CharField(max_length=100)),
                ('date_parution', models.DateField(blank=True, null=True)),
                ('prix', models.IntegerField()),
                ('genre', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
