# Generated by Django 5.2.1 on 2025-05-21 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Django', '0002_jeux_resume'),
    ]

    operations = [
        migrations.CreateModel(
            name='App_Django',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('franchise', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
