# Generated by Django 5.2.1 on 2025-05-23 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Django', '0003_studiodev'),
    ]

    operations = [
        migrations.AddField(
            model_name='jeux',
            name='studiodev',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='App_Django.studiodev'),
        ),
    ]
